### ISSUE TITLE
CV links point to a 404 page

### ISSUE THREAD

**Issue by casassg** [hackupc/registration#15]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG

## What happened

- Review application
- Click link to CV
- Get 404 page 

## What you expected to happen

- CV visualization

## Anything else we need to know?

Nope

## Environment
- Browser version (Ex: Google Chrome 62.0.3202.94 (64-bit)...): Chrome 67.0.3396.99 (Official Build) (64-bit)
- Domain: my.hackupc.com

**Comment by casassg** [comment]
@oriolclosa I think this may be due to a missing config in the nginx file. Check that my.hackupc.com has this in it:

```
location /files/ {
        alias /home/user/project_folder/files/;
    }
```

**Comment by oriolclosa** [comment]
This solved it, thank-you!
